CREATE TABLE `scholarships` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fname` varchar(32) DEFAULT NULL,
  `lname` varchar(32) DEFAULT NULL,
  `email` varchar(64) DEFAULT NULL,
  `telephone` varchar(16) DEFAULT NULL,
  `address` text,
  `country` varchar(32) DEFAULT NULL,
  `nationality` varchar(64) DEFAULT NULL,
  `residence` varchar(64) DEFAULT NULL,
  `haspassport` tinyint(1) DEFAULT NULL,  
  -- `passport` varchar(32) DEFAULT NULL,
  `airport` varchar(64) DEFAULT NULL,
  `languages` varchar(64) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `sex` enum('m', 'f', 'd'),
  `occupation` varchar(64),
  `areaofstudy` varchar(64),
  `wm05` tinyint(1) DEFAULT NULL,
  `wm06` tinyint(1) DEFAULT NULL,
  `wm07` tinyint(1) DEFAULT NULL,
  `wm08` tinyint(1) DEFAULT NULL,
  `wm09` tinyint(1) DEFAULT NULL,
  `wm10` tinyint(1) DEFAULT NULL,
  `priorrecipient` tinyint(1) DEFAULT NULL,
  `presentation` tinyint(1) DEFAULT NULL,
  `howheard` text,
  `why` text,
  `username` varchar(64) DEFAULT NULL,
  `project` text,
  `projectlangs` text,
  `involvement` text,
  `contribution` text,
  -- `bio` text,
  -- `departing` text,
  -- `dates` text,
  -- `cost` float DEFAULT NULL,
  -- `total` float DEFAULT NULL,
  -- `external` tinyint(1) DEFAULT NULL,
  -- `reimburse` tinyint(1) DEFAULT NULL,
  -- `visa` tinyint(1) DEFAULT NULL,
  -- `applied` tinyint(1) DEFAULT NULL,
  -- `visaext` text,
  -- `misc` text,
  `sincere` tinyint(1) NOT NULL DEFAULT '0',
  `honest` tinyint(1) NOT NULL DEFAULT '0',
  `agreestotravelconditions` tinyint(1) NOT NULL DEFAULT '0',
  `willgetvisa` tinyint(1) NOT NULL DEFAULT '0',
  `willpayincidentals` tinyint(1) NOT NULL DEFAULT '0',
  `rank` int(11) NOT NULL DEFAULT '0',
  `notes` text,
  `exclude` tinyint(1) NOT NULL DEFAULT '0',
  `confirmed` tinyint(1) NOT NULL DEFAULT '0',
  `confhash` varchar(8) DEFAULT NULL,
  -- `whenconf` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `entered_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- added by CB 4/9/09
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1434 DEFAULT CHARSET=latin1;
